### ISSUE TITLE
$HOME/.instrbuilder should be created earlier in the README?

### ISSUE THREAD

**Issue by brainstorm** [lucask07/instrbuilder#22]
```
$ ./rigol_instrbuilder_yaml_create.py
Error:  <class 'ImportError'>
IC (integrated circuit imports failed)
The aardvark.so or dll must be in the cwd or an importable path
Continuing anyways, since many may not use this portion...
Traceback (most recent call last):
  File "./rigol_instrbuilder_yaml_create.py", line 4, in <module>
    instrument_opening.init_yaml(csv_dir = '.')
  File "/Users/romanvg/.miniconda/envs/modbus/lib/python3.6/site-packages/instrbuilder/instrument_opening.py", line 66, in init_yaml
    with open(os.path.join(home, filename), 'w+') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/romanvg/.instrbuilder/config.yaml'

$ mkdir -p ~/.instrbuilder
$ ./rigol_instrbuilder_yaml_create.py
Error:  <class 'ImportError'>
IC (integrated circuit imports failed)
The aardvark.so or dll must be in the cwd or an importable path
Continuing anyways, since many may not use this portion...
$
```

**Comment by lucask07** [comment]
Thanks @brainstorm 
This was an error in the code that did not create the folder if needed. Within the function ```init_yaml``` I've added:

```
try: 
   os.mkdir(home)
except FileExistsError:
   pass
```

Release 0.1.7 has this fix and has been updated to pypi. 
Thank you for noting this issue!
